services:
  guacd:
    image: guacamole/guacd:${GUAC_VERSION}
    container_name: guacd
    restart: unless-stopped
    networks:
      - caddy

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: guac-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password
    networks:
      - caddy

  guacamole:
    image: guacamole/guacamole:${GUAC_VERSION}
    container_name: guacamole
    depends_on: [guacd, postgres]
    restart: unless-stopped
    # No host port published; Caddy will reverse-proxy internally
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/db_user
      # Guacamole image doesn’t support POSTGRES_PASSWORD_FILE,
      # so we inject it via entrypoint wrapper below.
    volumes:
      - ${CONFIG_DIR}:/etc/guacamole
      - ${RECORDINGS_DIR}:/var/lib/guacamole/recordings
    entrypoint: ["/bin/sh", "-c", "\
      export POSTGRES_PASSWORD=$(cat /run/secrets/db_password); \
      exec /opt/guacamole/bin/start.sh "]
    secrets:
      - db_user
      - db_password
    networks:
      - caddy

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password

networks:
  caddy:
    external: true
    name: ${CADDY_NETWORK}