services:
  guacd:
    image: guacamole/guacd:${GUAC_VERSION}
    platform: linux/amd64
    container_name: guacd
    restart: unless-stopped
    networks:
      - caddy

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: guac-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data
    networks:
      - caddy

  guacamole:
    image: guacamole/guacamole:${GUAC_VERSION}
    platform: linux/amd64
    container_name: guacamole
    depends_on: [guacd, postgres]
    restart: unless-stopped
    # No host port published; Caddy will reverse-proxy internally
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${CONFIG_DIR}:/etc/guacamole
      - ${RECORDINGS_DIR}:/var/lib/guacamole/recordings
    networks:
      - caddy

networks:
  caddy:
    external: true
    name: ${CADDY_NETWORK}